"""Shared lifecycle contract implemented by both agent backends."""

from __future__ import annotations

from collections.abc import Awaitable, Callable
from typing import Protocol

from .config import ProjectConfig


class SessionController(Protocol):
    def project(self, name: str) -> ProjectConfig | None: ...

    def names(self) -> list[str]: ...

    def last_model(self, project: str) -> str | None: ...

    def add_projects(self, projects: list[ProjectConfig]) -> int: ...

    def is_running(self, name: str) -> bool: ...

    async def start_all(self) -> None: ...

    async def deliver(self, project: str, text: str) -> None: ...

    async def interrupt(self, project: str) -> bool: ...

    async def set_enabled(self, project: str, enabled: bool) -> None: ...

    async def set_mode(self, project: str, mode: str) -> None: ...

    async def set_effort(self, project: str, level: str) -> None: ...

    async def set_verbose(self, project: str | None, on: bool) -> None: ...

    async def stop_all(self) -> None: ...
